---
# Manage the Seeed Odyssey J1405 SBC server built into the Hab.
#
# The server connects to the hab environmental components
# via USB, GPIO, I2C and SPI. Application containers handling
# those components are hosted by nomad.
#
# This play sets up the server and container hosting environment.

# Install packages

- name: Installing apt packages
  ansible.builtin.apt:
    name: "{{item}}"
  loop:
    - chrony
    - docker.io
    - influxdb
    - postgresql

# Install Hashicorp nomad, consul and vault

- name: Add Hashicorp apt repository key
  ansible.builtin.copy:
    src: files/usr/share/keyrings/hashicorp.gpg
    dest: /usr/share/keyrings/hashicorp.gpg
  register: hashicorp_apt_key

- name: Add Hashicorp apt repository
  ansible.builtin.copy:
    src: files/etc/apt/sources.list.d/hashicorp.list
    dest: /etc/apt/sources.list.d/hashicorp.list
  register: hashicorp_apt_repo

- name: Update apt index
  ansible.builtin.apt:
    update_cache: yes
  when: hashicorp_apt_key.changed or hashicorp_apt_repo.changed

- name: Install Hashicorp services
  ansible.builtin.apt:
    name: "{{item}}"
  loop:
    - consul
    - vault
    - nomad

# Configure the Hashicorp services

- name: Configure Hashicorp services
  ansible.builtin.copy:
    src: "files/etc/{{item}}"
    dest: "/etc/{{item}}"
  loop:
    - consul.d/consul.hcl
    - vault.d/vault.hcl
    - nomad.d/nomad.hcl

# Enable and start Hashicorp services

- name: Enable and start Hashicorp services
  ansible.builtin.systemd:
    name: "{{item}}"
    state: started
    enabled: yes
  loop:
    - consul
    - vault
    - nomad
