[tool.poetry]
name = "infrastructure"
version = "0.1.0"
description = ""
authors = ["David Kern <david@mju.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ansible = "^7.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
