west := "$HOME/zephyrproject/.venv/bin/west -z $HOME/zephyrproject/zephyr"

help:
    just -l

# build the firmware
build:
    {{west}} build -b nrf5340dk_nrf5340_cpuapp . -p

# run a west command
west *args:
    {{west}} {{args}}
